version: '3'

networks:
  rinha-network:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    tty: true
    ports:
      - '9999:9999'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha-network
    depends_on:
      - api

  api:
    build:
      context: .
    volumes:
      - ./api:/var/www/html
      - ./docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
    expose:
      - 80
    networks:
      - rinha-network
    depends_on:
      - db

  db:
    image: postgres:11
    # restart: unless-stopped
    environment:
      POSTGRES_USER: 'rinha'
      POSTGRES_PASSWORD: 'rinhapass'
    networks:
      - rinha-network
