version: '3'

networks:
  rinha-network:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    tty: true
    ports:
      - '9999:9999'
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha-network
    depends_on:
      - api
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 512MB

  api:
    build:
      args:
        user: roberto
        uid: 1000
        timezone: America/Manaus
      context: .
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    expose:
      - 80
      - 9000
    environment:
      APP_URL: http://localhost
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: rinha
      DB_USERNAME: rinha
      DB_PASSWORD: rinhapass
    networks:
      - rinha-network
    depends_on:
      - db
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.2'
          memory: 512MB

  db:
    image: postgres:11
    # restart: unless-stopped
    environment:
      POSTGRES_USER: 'rinha'
      POSTGRES_PASSWORD: 'rinhapass'
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1536MB
