name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: docker build . -t rinha-de-backend-2023-q3

  php-test-with-db:
    name: Lumen run tests with posgres
    needs: build
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: rinha
          POSTGRES_PASSWORD: rinhapass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: ctype, fileinfo, json, pdo

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Install Composer Dependencies
        run: composer install --no-scripts --prefer-dist

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: ./vendor/bin/phpunit
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: rinha
          DB_USERNAME: rinha
          DB_PASSWORD: rinhapass

  stress-test:
    runs-on: ubuntu-20.04
    needs: build
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - run: docker-compose up -d

      - name: Load test
        run: |
          git clone --single-branch --quiet https://github.com/zanfranceschi/rinha-de-backend-2023-q3
          cd rinha-de-backend-2023-q3
          # git checkout 4ffa657e3140002c7990b1ff476b58b4a043d932
          wget https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.9.5/gatling-charts-highcharts-bundle-3.9.5-bundle.zip
          unzip gatling-charts-highcharts-bundle-3.9.5-bundle.zip
          cd gatling-charts-highcharts-bundle-3.9.5
          ./bin/gatling.sh -rm local -s RinhaBackendSimulation -rd "${{ github.sha }}" -rf $WORKSPACE/user-files/results -sf $WORKSPACE/user-files/simulations -rsf $WORKSPACE/user-files/resources
          echo GATLING_OUTPUT_FOLDER=$(ls $WORKSPACE/user-files/results | sort | head -n 1) >> $GITHUB_ENV
        env:
          WORKSPACE: ${{ github.workspace }}/rinha-de-backend-2023-q3/stress-test

      - run: echo "contagem de pessoas -> $(curl -v 'http://localhost:9999/contagem-pessoas')" >> "${GITHUB_STEP_SUMMARY}"

      - run: docker-compose ps

      - run: docker-compose logs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/rinha-de-backend-2023-q3/stress-test/user-files/results/${{ env.GATLING_OUTPUT_FOLDER }}
          destination_dir: ${{ env.GATLING_OUTPUT_FOLDER }}

      - run: echo "GH_REPO=$(echo ${{ github.repository }} | cut -d "/" -f 2)" >> $GITHUB_ENV

      - run: echo "[Deploying to https://${{ github.repository_owner }}.github.io/${{ env.GH_REPO }}/${{ env.GATLING_OUTPUT_FOLDER }}](https://${{ github.repository_owner }}.github.io/${{ env.GH_REPO }}/${{ env.GATLING_OUTPUT_FOLDER }})" >> "${GITHUB_STEP_SUMMARY}"
